#!/usr/local/bin/gmake -f

.ONESHELL:

generate:
	./godown --verbose 2&> verbose.log
	
diff:
	diff godown.go godown.go.expected || true
	diff main.go main.go.expected || true
	
build:
	go build
	
build-by-godown:
	./godown build
	
build-and-notarize:
	goreleaser build --snapshot --rm-dist
	
check-notarized:
	@echo Check the binary is signed
	codesign --display -vvv dist/macos_darwin_amd64_v1/godown
	
	@echo
	@echo Check the binary is notarized
	spctl --assess --type install -vvv dist/macos_darwin_amd64_v1/godown
	
build-and-release-snapshot:
	goreleaser release --snapshot --rm-dist
	
build-and-release:
	goreleaser release --rm-dist
	
hello:
	cd tests/hello
	# clean up
	if [ -e hello.go ]; then
	  rm hello.go
	fi
	if [ -e hello ]; then
	  rm hello
	fi
	# generate *.go files
	../../godown
	# check diff
	diff hello.go hello.go.expected > hello.go.diff
	cat hello.go.diff
	# build the generated *.go files
	../../godown build
	# run it
	./hello
	# another way to run
	../../godown run hello.go.md
	

# This makefile is generated by makedown from "Makefile.md"
